### PR TITLE
Check event.user is not null

### PR DESCRIPTION
**Pull request by fedealconada**
This avoids problems when botpress uses both this and botpress-webhooks modules at the same time.

### CODE REVIEW

**Comment by slvnperron** [comment]
Hey federico! Could you please sign the CLA so I can merge this?

Thanks

**Comment by jbuchacher** [comment]
Any chance this can get merged? Thanks in advance!

**Comment by slvnperron** [comment]
@jbuchacher Done and pushed in newest version!

**Comment by fedealconada** [comment]
Nice :)

**Pull request merged**
